language: r
cache: packages
Title: Package for Lab3: Euclidean and Dijkstra Functions
Version: 1.0
Date: 2020-09-10
Author: Who wrote it
Maintainer: Who to complain to <yourfault@somewhere.net>
Description: More about what it does (maybe more than one line)
License: What license is it under?
Encoding: UTF-8
RoxygenNote: 7.1.1
